version: '2'
services:
  app:
    build: .
    volumes:
      - ./input:/home/files/input
      - ./output:/home/files/output
    ports:
      - "9080:8080"
      - "9443:8443"
    environment:
      MIRTH_DB_USERNAME: mirth
      MIRTH_DB_PASSWORD: mirth
      MIRTH_DB_HOST: db
      MIRTH_DB_NAME: mirthdb
      KEYSTORE_PASS: p\*AA[7E>s`5E2bx
      KEYSTORE_KEYPASS: p\*AA[7E>s`5E2bx
    depends_on:
      - db
  db:
    image: postgres:9.4
    environment:
      POSTGRES_PASSWORD: mirth
      POSTGRES_USER: mirth
      POSTGRES_DB: mirthdb
    volumes:
      - data:/var/lib/postgresql/data
volumes:
  data:
    driver: local
